.TH logic_rdm_sniffer 1 "December 2013"
.SH NAME
logic_rdm_sniffer \- Decode DMX/RDM data from a Saleae Logic device.
.SH SYNOPSIS
logic_rdm_sniffer [ options ]
.SH DESCRIPTION
logic_rdm_sniffer
Decode DMX/RDM data from a Saleae Logic device.
.SH OPTIONS
.IP "-d, --display-dmx"
Display DMX Frames. Defaults to false.
.IP "-h, --help"
Display the help message
.IP "-l, --log-level <int8_t>"
Set the logging level 0 .. 4.
.IP "-r, --full-rdm"
Unpack RDM parameter data.
.IP "-t, --timestamp"
Include timestamps.
.IP "--display-asc"
Display non-RDM alternate start code frames.
.IP "--dmx-slot-limit <uint16_t>"
Only display the first N slots of DMX data.
.IP "--no-use-epoll"
Disable the use of epoll(), revert to select()
.IP "--pid-location <string>"
The directory containing the PID definitions.
.IP "--sample-rate <uint32_t>"
Sample rate in HZ.
.IP "--syslog"
Send to syslog rather than stderr.
.IP "-v, --version"
Print
.B logic_rdm_sniffer
version information
.SH EXAMPLES
.SS Display RDM messages from the Logic device.
logic_rdm_sniffer -r
.SS Display RDM and DMX frames from the Logic device.
logic_rdm_sniffer -r -d
