dist_man_MANS += \
    man/logic_rdm_sniffer.1 \
    man/ola_artnet.1 \
    man/ola_dev_info.1 \
    man/ola_dmxconsole.1 \
    man/ola_dmxmonitor.1 \
    man/ola_e131.1 \
    man/ola_patch.1 \
    man/ola_plugin_info.1 \
    man/ola_plugin_state.1 \
    man/ola_rdm_discover.1 \
    man/ola_rdm_get.1 \
    man/ola_rdm_set.1 \
    man/ola_recorder.1 \
    man/ola_set_dmx.1 \
    man/ola_set_priority.1 \
    man/ola_streaming_client.1 \
    man/ola_timecode.1 \
    man/ola_trigger.1 \
    man/ola_uni_info.1 \
    man/ola_uni_merge.1 \
    man/ola_uni_name.1 \
    man/ola_uni_stats.1 \
    man/ola_usbpro.1 \
    man/olad.1 \
    man/rdm_model_collector.py.1 \
    man/rdm_responder_test.py.1 \
    man/rdm_test_server.py.1 \
    man/rdmpro_sniffer.1 \
    man/sigrok_rdm_sniffer.1 \
    man/usbpro_firmware.1
