.TH ola_set_priority 1 "July 2013"
.SH NAME
ola_set_priority \- Set an olad port's priority.
.SH SYNOPSIS
.B ola_set_priority [ options ]
.SH DESCRIPTION
.B ola_set_priority
is used to set the priority of ports in olad(1).
.SH OPTIONS
.IP "-h, --help"
Display the help message.
.IP "-d, --device <device>"
Id of the device you want to set the priority of.
.IP "-i, --input"
Set an input port, otherwise set an output port.
.IP "-o, --override <value>"
Set the port priority to a static value, if this option isn't used, the port
will be set to inherit mode.
.IP "-p, --port <port>"
Id of the port you want to set the priority of.
.SH SEE ALSO
.BR olad(1) ,
.BR ola_dev_info(1) ,
.
