.TH ola_e131 1 "July 2013"
.SH NAME
ola_e131 \- Configure E1.31 devices managed by OLA.
.SH SYNOPSIS
.B ola_e131 [ options ]
.SH DESCRIPTION
.B ola_e131
is used to configure E1.31 devices managed by OLA.
.SH OPTIONS
.IP "-h, --help"
Display the help message.
.IP "-d, --dev <device>"
Id of the device to control.
.IP "-i, --input"
Set an input port, otherwise set an output port.
.IP "-p, --port-id <port>"
Id of the port you want to control.
.IP "--preview-mode <on|off>"
Set the preview mode bit.
.SH SEE ALSO
.BR olad(1) ,
.
