.TH ola_usbpro 1 "July 2013"
.SH NAME
ola_usbpro \- Configure Enttec USB Pro Devices managed by OLA.
.SH SYNOPSIS
.B ola_usbpro [ options ]
.SH DESCRIPTION
.B ola_usbpro
is used to query and control the parameters of Enttec USB Pro devices. 
.SH OPTIONS
.IP "-h, --help"
Display the help message.
.IP "-a, --assignments"
Get the port assignments.
.IP "-b, --brk <break>"
Set the break time (9 - 127)
.IP "-d, --dev <device>"
The device to configure
.IP "-m, --mab <mab>"
Set the make after-break-time (1 - 127)
.IP "-p, --port <port>
The port to configure
.IP "-r, --rate <rate>"
Set the transmission rate (1 - 40).
.IP "-s, --serial"
Get the serial number.
.SH SEE ALSO
.BR olad(1) ,
.
