.TH ola_uni_name 1 "June 2015"
.SH NAME
ola_uni_name \- Set the name for a universe in olad.
.SH SYNOPSIS
.B ola_uni_name
--name <name> --universe <uni>
.SH DESCRIPTION
.B ola_uni_name
is used to set the name for a universe.
.SH OPTIONS
.IP "-n, --name <name>"
Name for the universe.
.IP "-u, --universe <universe>"
Id of the universe to name.
.IP "-h, --help"
Display the help message
.SH SEE ALSO
.BR olad(1) ,
.
