.TH ola_streaming_client 1 "July 2013"
.SH NAME
ola_streaming_client \- Stream data to the OLA server.
.SH SYNOPSIS
.B ola_streaming_client [ options ]
.SH DESCRIPTION
.B ola_streaming_client
is used to stream DMX512 data to olad(1). If DMX512 data isn't provided, it
will read from STDIN.
.SH OPTIONS
.IP "-h, --help"
Display the help message.
.IP "-d, --dmx <dmx data>"
Comma separated DMX values to send, e.g. 0,255,128 sets first channel to 0, second channel to 255 and third channel to 128.
.IP "-l, --log-level <int8_t>"
Set the logging level 0 .. 4.
.IP "-s, --universe-from-stdin"
Also read the destination universe number from STDIN when reading DMX data from STDIN. The universe number must precede the channel values, and be delimited by whitespace. E.g. 1 0,255,128 2 0,255,127.
.IP "-u, --universe <universe-id>"
Id of the universe to send data for.
.IP "-v, --version"
Print
.B ola_streaming_client
version information
.IP "--syslog"
Send to syslog rather than stderr.
.IP "--no-use-epoll"
Disable the use of epoll(), revert to select()
.IP "--no-use-kqueue"
Disable the use of kqueue(), revert to select()
.IP "--scheduler-policy <policy>"
The thread scheduling policy, one of {fifo, rr}.
.IP "--scheduler-priority <priority>"
The thread priority, only used if --scheduler-policy is set.
.SH SEE ALSO
.BR olad(1) ,
.
