.TH ola_artnet 1 "July 2013"
.SH NAME
ola_artnet \- Configure Art-Net devices managed by OLA.
.SH SYNOPSIS
.B ola_artnet
-d <device_id> -n <name> -l <long_name> -s <subnet>
.SH DESCRIPTION
.B ola_artnet
is used to configure Art-Net devices managed by OLA.
.SH OPTIONS
.IP "-d, --device <device>"
Id of the Art-Net device to configure.
.IP "--net <network>"
Set the net parameter of the Art-Net device.
.IP "-h, --help"
Display the help message
.IP "-l, --log-level <int8_t>"
Set the logging level 0 .. 4.
.IP "-n, --name <name>"
Set the name of the Art-Net device.
.IP "-s, --subnet <subnet>"
Set the subnet parameter of the Art-Net device.
.IP "-u, --universe <universe-id>"
List the IPs of Art-Net devices for this universe.
.IP "-v, --version"
Display version information
.IP "--long-name <long-name>"
Set the long name of the Art-Net device.
.IP "--syslog"
Send to syslog rather than stderr.
.IP "--no-use-epoll"
Disable the use of epoll(), revert to select()
.IP "--no-use-kqueue"
Disable the use of kqueue(), revert to select()
.IP "--scheduler-policy <policy>"
The thread scheduling policy, one of {fifo, rr}.
.IP "--scheduler-priority <priority>"
The thread priority, only used if --scheduler-policy is set.
.SH SEE ALSO
.BR olad(1) ,
.
