.TH ola_dmxmonitor 1 "March 2013"
.SH NAME
ola_dmxmonitor \- Monitor the values on a DMX512 universe.
.SH SYNOPSIS
.PP
.B ola_dmxmonitor 
.RI [ option "...]"
.PP
.SH DESCRIPTION
.B ola_dmxmonitor
is a piece of software that lets you monitor the values on an
.B OLA
DMX512 universe 
.PP
.PP
.SH OPTIONS
\fB\-u\fInumber\fP, \fB\-\-universe=\fP\fInumber\fP
The universe ID to monitor 
.TP
.BR \-h ", " \-\-help
Displays a short help message.
.SH ENVIRONMENT
None
.SH SEE ALSO
.BR ola(1) ,
.BR olad(1) ,
.BR /usr/share/doc/ola/README
.
