.TH ola_uni_merge 1 "June 2015"
.SH NAME
ola_uni_merge \- Set the merge mode for a universe in olad.
.SH SYNOPSIS
.B ola_uni_merge
--universe <uni> [--ltp]
.SH DESCRIPTION
.B ola_uni_merge
is used to set the merge mode for a universe. Without --ltp it will revert to
HTP mode.
.SH OPTIONS
.IP "-l, --ltp"
Change to LTP mode.
.IP "-u, --universe <universe>"
Id of the universe to name.
.IP "-h, --help"
Display the help message
.SH SEE ALSO
.BR olad(1) ,
.
