.TH ola_plugin_info 1 "June 2015"
.SH NAME
ola_plugin_info \- Get info on the plugins loaded by olad.
.SH SYNOPSIS
.B ola_plugin_info
[--plugin-id <plugin-id>] [--list-plugin-ids]
.SH DESCRIPTION
.B ola_plugin_info
is used to get info on the plugins loaded by olad. With no arguments it shows
the name and id of the loaded plugins.
.SH OPTIONS
.IP "-h, --help"
Display the help message
.IP "-p, --plugin-id <plugin_id>"
Id of the plugin to fetch the description of.
.IP "--list-plugin-ids"
List just the ids of the plugins loaded by olad.
.SH SEE ALSO
.BR olad(1) ,
.
