#!/bin/sh

ltmain=/usr/share/libtool/ltmain.sh

if [ \( ! -f config/ltmain.sh \) -a \( -f $ltmain \) ]; then
	ln -s $ltmain config/ltmain.sh
fi

pushd ./ > /dev/null
cd tools
echo "Generating source files..."
./generate.sh
popd > /dev/null

echo "Running autotools"
rm -f config.cache
set -x
aclocal -I config
autoconf
autoheader
automake -a
exit
