#!/bin/sh

ltmain=/usr/share/libtool/ltmain.sh

if [ \( ! -f config/ltmain.sh \) -a \( -f $ltmain \) ]; then
	ln -s $ltmain config/ltmain.sh
fi

pushd ./ > /dev/null
cd tools
echo "Generating source files..."
perl -e "use Template1" 2> /dev/null

if [ $? != 0 ]; then
  echo "ERROR: Could not find Template.pm, you need this to autogenerate\
 parts of the code"
  exit 1
fi
./generate.sh
popd > /dev/null

echo "Running autotools"
rm -f config.cache
set -x
aclocal -I config
autoconf
autoheader
automake -a
exit
