[% INCLUDE gpl.tmpl %]
/*
 * This code has been autogenerated, do not edit
 */

#ifndef [% module %][% name %]Msg_H
#define [% module %][% name %]Msg_H

#include <stdint.h>
#include "[% module FILTER lower %]_[% name FILTER lower %]_messages.h"

class [% module %][% name %]Msg {

  public:
    [% module %][% name %]Msg() {};
    virtual ~[% module %][% name %]Msg();

    virtual uint8_t *pack(int *len) = 0;
    virtual [% lib FILTER lower %]_[% module FILTER lower %]_[% name FILTER lower %]_msg_op type() = 0;
};

#endif
