[% INCLUDE $licence %]
/*
 * This code has been autogenerated, do not edit
 */

#ifndef [% module %][% name %]Msg_H
#define [% module %][% name %]Msg_H

#include <stdint.h>
#include "[% module FILTER lower %]_[% name FILTER lower %]_messages.h"

[%- IF parent -%]
#include [% parent.include %]
[%- END %]

class [% module %][% name %]Msg [%- IF parent -%] : public [% parent.name %] [%- END -%] {

  public:
    [% module %][% name %]Msg() {};
    virtual ~[% module %][% name %]Msg() {};

    virtual int pack(uint8_t *buf, int len) const= 0;
    virtual [% lib FILTER lower %]_[% module FILTER lower %]_[% name FILTER lower %]_msg_op type() = 0;
};

#endif
