[% INCLUDE $licence %]
/*
 * This code has been autogenerated, do not edit
 */

[%- MACRO publics(type) BLOCK %]
    [% type %] get_[% var %]() const { return m_[% var %]; }
    void set_[% var %]([% type %] v) { m_[% var %] = v; }
[% END -%]

[%- MACRO array_publics(type) BLOCK %]
    static const int [% array.name FILTER upper %]_SIZE = [% array.len %];
    const [% type %] *get_[% array.name %](int *len) const;
    int get_[% array.name %]([% type %] *buf, int len) const;
    void set_[% array.name %]([% type %] *v, int len);
[% END -%]

#ifndef [% module %][% name %]Msg[% msg.cls_name %]_H
#define [% module %][% name %]Msg[% msg.cls_name %]_H

#include <stdio.h>

#include "[% module %][% name %]Msg.h"

class [% module %][% name %]Msg[% msg.cls_name %] : public [% module %][% name %]Msg {

  public:
    [% module %][% name %]Msg[% msg.cls_name %]();
    ~[% module %][% name %]Msg[% msg.cls_name %]();

    int pack(uint8_t *buf, int len) const;
    void print() const;
    [% lib FILTER lower %]_[% module FILTER lower %]_[% name FILTER lower %]_msg_op type() { return [% lib FILTER upper %]_[% module FILTER upper %]_[% name FILTER upper %]_MSG_[% msg.name FILTER upper %]; }

[% FOREACH var = msg.uint32_t -%]
   [% publics('uint32_t') -%]
[% END -%]
[% FOREACH var = msg.uint16_t -%]
   [% publics('uint16_t')  -%]
[% END -%]
[% FOREACH var = msg.uint8_t -%]
   [% publics('uint8_t') -%]
[% END -%]

[% FOREACH array = msg.array.uint32_t -%]
   [% array_publics('uint32_t') -%]
[% END -%]
[% FOREACH array = msg.array.uint16_t -%]
   [% array_publics('uint16_t') -%]
[% END -%]
[% FOREACH array = msg.array.uint8_t -%]
   [% array_publics('uint8_t') -%]
[% END -%]

  private:
[% FOREACH var = msg.uint32_t -%]
    uint32_t m_[% var %];
[% END -%]
[% FOREACH var = msg.uint16_t -%]
    uint16_t m_[% var %];
[% END -%]
[% FOREACH var = msg.uint8_t -%]
    uint8_t m_[% var %];
[% END -%]
[% FOREACH array = msg.array.uint32_t -%]
    uint32_t m_[% array.name %][[% array.len %]];
[% END -%]
[% FOREACH array = msg.array.uint16_t -%]
    uint16_t m_[% array.name %][[% array.len %]];
[% END -%]
[% FOREACH array = msg.array.uint8_t -%]
    uint8_t m_[% array.name %][[% array.len %]];
[% END -%]
};

#endif
