[% INCLUDE gpl.tmpl %]
/*
 * This code has been autogenerated, do not edit
 */

#include <stdio.h>

#include "[% module %][% name %]Msg.h"

class [% module %][% name %]Msg[% cls_name %] : public [% module %][% name %]Msg {

  public:
    [% module %][% name %]Msg[% cls_name %]();
	~[% module %][% name %]Msg[% cls_name %]();

    uint8_t *pack(int *len);
    [% lib FILTER lower %]_[% module FILTER lower %]_[% name FILTER lower %]_msg_op type() { return [% lib FILTER upper %]_[% module FILTER upper %]_[% name FILTER upper %]_MSG_[% msg.name FILTER upper %]; }

[% FOREACH var = msg.uint32_t -%]
    uint32_t get_[% var %]() { return m_[% var %]; }
    void set_[% var %](uint32_t v) { m_[% var %] = v; }
[% END -%]
[% FOREACH var = msg.uint16_t -%]
    uint16_t get_[% var %]() { return m_[% var %]; }
    void set_[% var %](uint32_t v) { m_[% var %] = v; }
[% END -%]
[% FOREACH var = msg.uint8_t -%]
    uint8_t get_[% var %]() { return m_[% var %]; }
    void set_[% var %](uint32_t v) { m_[% var %] = v; }
[% END -%]
[% FOREACH array = msg.array.uint32_t -%]
    const uint32_t *get_[% array.name %](int *len);
	void set_[% array.name %](uint32_t *v, int len);
[% END -%]
[% FOREACH array = msg.array.uint16_t -%]
    const uint16_t *get_[% array.name %](int *len);
	void set_[% array.name %](uint16_t *v, int len);
[% END -%]
[% FOREACH array = msg.array.uint8_t -%]
    const uint8_t *get_[% array.name %](int *len);
	void set_[% array.name %](uint8_t *v, int len);	
[% END -%]

  private:
[% FOREACH var = msg.uint32_t -%]
    uint32_t m_[% var %];
[% END -%]
[% FOREACH var = msg.uint16_t -%]
    uint16_t m_[% var %];
[% END -%]
[% FOREACH var = msg.uint8_t -%]
    uint8_t m_[% var %];
[% END -%]
[% FOREACH array = msg.array.uint32_t -%]
    uint32_t m_[% array.name %][[% array.len %]];
[% END -%]
[% FOREACH array = msg.array.uint16_t -%]
    uint16_t m_[% array.name %][[% array.len %]];
[% END -%]
[% FOREACH array = msg.array.uint8_t -%]
    uint8_t m_[% array.name %][[% array.len %]];
[% END -%]
};
