# GitHub Action to compile and test
name: compilation
on: [push, pull_request]
jobs:
  compile:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          brew update
          brew install ccache
          # This is all the bits we need to enable all options on Mac
          brew install bison
          brew install flex
          # Installing via the addon isn't currently working so do it the old fashioned way below
          # - https://raw.githubusercontent.com/Homebrew/homebrew-core/024ca9a4730a1f26ceede43485fbf62ef6f41179%5E/Formula/protobuf@3.1.rb
          brew install liblo
          brew install libmicrohttpd
          brew install ossp-uuid
          # Looks like this is Python 3 only, so install via pip
          # brew install numpy
          brew install libusb
          brew install protobuf
          brew install cppunit
      - name: Compile
        env:
          TASK: 'compile'
        run: |
          bash -ex .travis-ci.sh
