name: isort

on: [push, pull_request]

permissions:
  contents: read

jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: isort/isort-action@v1
