name: lint
on: [push, pull_request]
jobs:
  python-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: "python/ola python/examples tools/ola_mon tools/rdm"
          extra-pylint-options: --disable=C,W --disable=useless-object-inheritance,super-with-arguments --indent-string=\"  \"
