name: lint
on: [push, pull_request]
jobs:
  python-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: cd python/ola
      - run: ls -al
      - uses: ricardochaves/python-lint@v1.4.0
